name: template
description: template v20230601

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # api interaction
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.6

  # services
  go_router: ^8.0.0
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
#  audioplayers: ^4.0.0

  # custom
  flutter_secure_storage: ^8.0.0

  # utility
  awesome_dialog: ^3.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.0
  test: ^1.19.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon-adaptive-foreground.png"